#![allow(unknown_lints)]
#![allow(clippy::literal_string_with_formatting_args)] // Keep allowing this for formatdoc! usage
use std::fmt::Display;

use indoc::formatdoc; // Using formatdoc for cleaner multiline strings

use crate::shell::{ActivateOptions, Shell};

#[derive(Default)]
pub struct Cmd {}

impl Shell for Cmd {
    fn activate(&self, opts: ActivateOptions) -> String {
        // Prepare mise executable path for Lua: escape backslashes
        let exe_lua_escaped = opts.exe.to_string_lossy().replace('\\', "\\\\");
        // Note: We will wrap the {exe} variable in quotes inside the Lua script
        //       to handle potential spaces in the path for cmd.exe execution.

        // The prelude might contain initial setup commands (e.g., setting environment variables)
        let prelude = self.format_activate_prelude(&opts.prelude);

        let _flags = opts.flags;

        // Generate the main Lua script content using formatdoc!
        // This incorporates the logic from the reviewed 'clink_mise_lua_fix_v1' script,
        // *minus* the non-existent clink.onclosing hook.
        formatdoc! {r#"
            {prelude}
            --[[
            Clink Lua script for integrating the 'mise' tool (https://github.com/jdx/mise)
            Generated by: mise activate cmd
            --]]

            -- ** IMPORTANT: Path configured by mise activate **
            local mise_exe_path = "{exe_lua_escaped}"

            -- Set environment variables that mise might use
            os.setenv("MISE_SHELL", "cmd")
            -- Store the original PATH if mise needs it (though mise hook-env usually handles PATH)
            -- It's generally safer *not* to modify __MISE_ORIG_PATH unless mise specifically requires it.
            -- Consider removing the line below if not strictly needed by your mise setup.
            -- os.setenv("__MISE_ORIG_PATH", os.getenv("PATH"))

            -- Store state in a local table to avoid polluting the global namespace too much
            local mise_state = {{
                prev_dir = nil,
                script_file = nil, -- Will store the path to the temporary script
                mise_exe_path = mise_exe_path
            }}

            -- Helper function to check if a table contains a value
            local function contains(tbl, value)
                if not tbl then return false end
                for _, v in ipairs(tbl) do
                    if v == value then
                        return true
                    end
                end
                return false
            end

            -- Helper function to parse arguments from a single string (basic quote handling)
            -- Note: This is a simple parser and may not handle all edge cases perfectly,
            --       especially complex nested or escaped quotes.
            local function parse_args(args_str)
                local args = {{}} -- Correctly initialize as an empty table
                local current_arg = ""
                local in_quotes = false
                args_str = args_str or "" -- Ensure it's a string

                for i = 1, #args_str do
                    local char = args_str:sub(i, i)
                    if char == '"' then
                        in_quotes = not in_quotes
                    elseif char == ' ' and not in_quotes then
                        if #current_arg > 0 then
                            table.insert(args, current_arg)
                            current_arg = ""
                        end
                    else
                        current_arg = current_arg .. char
                    end
                end

                if #current_arg > 0 then
                    table.insert(args, current_arg)
                end

                return args
            end

            -- Helper function to safely execute Lua code strings (like environment hooks)
            local function safe_load_and_run(code_string, error_prefix)
                error_prefix = error_prefix or "Error executing code"
                if not code_string or code_string == "" then
                    -- print(error_prefix .. ": No code to execute.") -- Optional: uncomment for debugging
                    return true -- Nothing to run, not an error
                end

                -- Attempt to load the string as a Lua chunk
                local chunk, err = load(code_string, "mise_hook_code", "t") -- Use text mode

                if chunk then
                    -- Execute the chunk in a protected call
                    local success, exec_err = pcall(chunk)
                    if not success then
                        print(error_prefix .. ": " .. tostring(exec_err))
                        return false
                    end
                    return true -- Success
                else
                    -- Handle syntax errors or other load errors
                    print(error_prefix .. ": Load error: " .. tostring(err))
                    return false
                end
            end


            -- Function to run the mise hook-env and apply changes
            function _mise_hook()
                -- Check if the shell is cmd (as expected by the hook argument)
                if os.getenv("MISE_SHELL") == "cmd" then
                    -- Construct the command to get environment hooks
                    -- Wrap executable path in quotes for cmd.exe
                    -- Note: {_flags} from ActivateOptions is not used here per the target script.
                    local cmd = string.format('"%s" hook-env -s cmd', mise_state.mise_exe_path)
                    -- print("Running hook:", cmd) -- Optional: uncomment for debugging

                    -- Execute the command and capture output
                    local handle = io.popen(cmd)
                    if not handle then
                        print("Error: Failed to run mise hook-env command.")
                        return
                    end

                    local result = handle:read("*a") -- Read all output
                    handle:close() -- Important to close the handle

                    -- print("Hook output:", result) -- Optional: uncomment for debugging

                    -- Safely load and execute the Lua code returned by the hook
                    safe_load_and_run(result, "Error applying mise hook")
                else
                    -- Optional: Handle cases where MISE_SHELL is not 'cmd' if needed
                    -- print("Mise hook skipped: MISE_SHELL is not 'cmd'.")
                end
            end


            -- Function to handle the 'mise' command invoked via doskey
            local function mise_handler(args_str)
                local args = parse_args(args_str)

                -- If no arguments are passed to 'mise', just run mise itself (shows help/version)
                if #args == 0 then
                    -- Wrap executable path in quotes for cmd.exe
                    os.execute(string.format('"%s"', mise_state.mise_exe_path))
                    -- Run the hook afterwards, as even running 'mise' might trigger env changes
                    -- if in a directory with a mise config.
                    _mise_hook()
                    return
                end

                local command = args[1]
                table.remove(args, 1) -- Remaining elements are arguments to the command

                -- Join remaining args back into a string suitable for passing to the executable
                -- We need to handle potential spaces in arguments by quoting them for cmd.exe
                local command_args_str = ""
                for _, arg in ipairs(args) do
                    -- Basic quoting: if arg contains space, wrap in quotes
                    if string.find(arg, " ", 1, true) then
                        command_args_str = command_args_str .. ' "' .. arg .. '"'
                    else
                        command_args_str = command_args_str .. ' ' .. arg
                    end
                end

                -- Commands that modify the shell environment directly (output Lua code)
                if command == "deactivate" or command == "shell" or command == "sh" then
                    -- Check for help flags for these specific commands *before* trying to capture output
                    if contains(args, "-h") or contains(args, "--help") then
                        -- If help is requested, just execute normally to display mise's help
                        -- Wrap executable path in quotes for cmd.exe
                        os.execute(string.format('"%s" %s%s', mise_state.mise_exe_path, command, command_args_str))
                        -- No hook needed after help
                    else
                        -- Execute the command and capture its output (expected to be Lua code)
                        -- Wrap executable path in quotes for cmd.exe
                        local cmd = string.format('"%s" %s%s', mise_state.mise_exe_path, command, command_args_str)
                        local handle = io.popen(cmd)
                        if not handle then
                            print("Error: Failed to run mise command:", command)
                            return
                        end
                        local result = handle:read("*a")
                        handle:close()

                        -- Safely load and execute the resulting Lua code
                        safe_load_and_run(result, "Error executing mise command '" .. command .. "'")
                        -- No separate hook needed, as the command output *is* the hook/change
                    end
                else
                    -- For all other commands, execute them directly
                    -- Wrap executable path in quotes for cmd.exe
                    local cmd = string.format('"%s" %s%s', mise_state.mise_exe_path, command, command_args_str)
                    -- print("Executing:", cmd) -- Optional: uncomment for debugging
                    os.execute(cmd) -- We don't capture output, just run the command

                    -- Run the hook afterwards, as any command might change the environment
                    -- based on mise configuration files (.mise.toml, etc.)
                    _mise_hook()
                end
            end

            -- Make the handler globally accessible ONLY for the temporary script
            _G._mise_internal_handler = mise_handler

            -- Create a temporary Lua script that doskey will call
            -- This script acts as a bridge, taking arguments from doskey ($*)
            -- and passing them to our main handler function.
            local script_content_template = [[
            -- Temporary script called by doskey 'mise' macro
            -- It receives all arguments as a single string via ...
            local args_str = ... or ""
            if _G._mise_internal_handler then
                -- Call the actual handler function with the argument string
                local success, err = pcall(_G._mise_internal_handler, args_str)
                if not success then
                    print("Error running mise handler:", err)
                end
            else
                print("Error: mise internal handler not found!")
            end
            ]]

            -- Create a temporary file for the script
            -- Using os.tmpname() is generally okay for clink scripts, but be aware
            -- it's not cryptographically secure if that's a concern.
            -- The 'mise deactivate' command should clean this up.
            local temp_script_path = os.tmpname() .. ".lua"
            local f, err = io.open(temp_script_path, "w")
            if f then
                f:write(script_content_template)
                f:close()
                mise_state.script_file = temp_script_path -- Store path for cleanup via deactivate
                -- print("Temporary script created at:", temp_script_path) -- Debugging
            else
                print("Error: Could not create temporary Lua script for mise doskey macro:", err)
                -- Abort setup if the script can't be created
                return -- Return early from the main script if setup fails
            end

            -- Create the doskey macro for 'mise'
            -- $* passes all arguments entered after 'mise' to the Lua script as a single string
            -- Escape the temp_script_path for the lua string.format call
            local lua_escaped_temp_script_path = string.gsub(mise_state.script_file, "\\", "\\\\")
            local doskey_command = string.format('doskey mise=lua "%s" $*', lua_escaped_temp_script_path)
            -- print("Setting doskey:", doskey_command) -- Debugging
            local handle, err_doskey = io.popen(doskey_command)
            if handle then
                handle:close() -- Close the handle immediately
            else
                print("Error: Failed to set doskey macro for mise:", err_doskey or "unknown error")
                -- Attempt cleanup even if doskey fails
                if mise_state.script_file then os.remove(mise_state.script_file) end
                return -- Return early from the main script if setup fails
            end

            -- Set up directory change hook using clink's event system
            mise_state.prev_dir = os.getcwd() -- Initialize current directory

            clink.onbeginedit(function()
                -- This function runs just before the command line becomes editable
                local current_dir = os.getcwd()
                if current_dir ~= mise_state.prev_dir then
                    -- print("Directory changed from", mise_state.prev_dir, "to", current_dir) -- Debugging
                    mise_state.prev_dir = current_dir
                    -- Run the environment hook when the directory changes
                    _mise_hook()
                end
                -- Return false to allow normal editing to begin
                return false
            end)

            -- NOTE: Automatic cleanup on shell exit is not available via a standard Clink hook.
            -- The temporary script file (mise_state.script_file) should be removed by
            -- running 'mise deactivate' or potentially by OS temp file cleanup.

            -- Run the hook once initially when the script loads
            -- print("Running initial mise hook...") -- Debugging
            _mise_hook()

            print("Mise integration loaded for clink.") -- Confirmation message

            -- End of generated script
        "#,
        prelude = prelude, // Pass prelude string for interpolation
        exe_lua_escaped = exe_lua_escaped, // Pass Lua-escaped exe path
        }
    }

    fn deactivate(&self) -> String {
        // This generates Lua code to be executed to undo the activation.
        // It cleans up the temporary script and doskey macro.
        formatdoc! {r#"
            -- Remove mise environment variables specific to the activation script
            os.setenv("MISE_SHELL", nil)
            -- Consider unsetting other variables set by hooks if necessary,
            -- though a full environment reload might be implied by deactivation.

            -- Remove mise function and macro
            io.popen("doskey mise="):close() -- Attempt to remove the doskey macro

            -- Remove the temporary script file using the path stored in mise_state (if available)
            if mise_state and mise_state.script_file then
                local removed, err_remove = os.remove(mise_state.script_file)
                if not removed then
                    print("Warning: Could not remove temporary mise script during deactivation:", mise_state.script_file, "Error:", err_remove or "unknown error")
                end
                mise_state.script_file = nil -- Clear path after attempting removal
            else
                -- Attempt to find and remove if state isn't available (less reliable)
                if _G._mise_internal_handler and _G._mise_internal_handler.script_file_path_for_cleanup then
                     local removed, err_remove = os.remove(_G._mise_internal_handler.script_file_path_for_cleanup)
                     if not removed then
                        print("Warning: Could not remove temporary mise script during deactivation (fallback):", _G._mise_internal_handler.script_file_path_for_cleanup, "Error:", err_remove or "unknown error")
                     end
                end
            end

            -- Clean up global handler reference
            _G._mise_internal_handler = nil

            -- Optional: Could try to unregister clink hooks, but clink might not have a direct API for that.
            -- They will become inactive when the session closes anyway.

            print("Mise integration deactivated.")
            "#}
    }

    fn set_env(&self, k: &str, v: &str) -> String {
        // Generate Lua code to set an environment variable.
        format!(
            "os.setenv(\"{}\", \"{}\")\n",
            escape_lua_string(k),
            escape_lua_string(v)
        )
    }

    fn prepend_env(&self, k: &str, v: &str) -> String {
        // Generate Lua code to prepend a value to an environment variable (like PATH).
        // Uses ';' as the separator for Windows PATH.
        format!(
            "os.setenv(\"{}\", \"{}\" .. \";\" .. (os.getenv(\"{}\") or \"\"))\n",
            escape_lua_string(k),
            escape_lua_string(v),
            escape_lua_string(k)
        )
    }

    fn unset_env(&self, k: &str) -> String {
        // Generate Lua code to unset an environment variable.
        format!("os.setenv(\"{}\", nil)\n", escape_lua_string(k))
    }
}

impl Display for Cmd {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "cmd")
    }
}

// Helper function to escape characters in a string for use within a Lua string literal
fn escape_lua_string(s: &str) -> String {
    s.replace('\\', "\\\\") // Escape backslashes first
        .replace('"', "\\\"") // Escape double quotes
        .replace('\n', "\\n") // Escape newlines
        .replace('\r', "\\r") // Escape carriage returns
        .replace('\t', "\\t") // Escape tabs
    // Add other escapes if needed (e.g., for other control characters)
}
